---
run:
  timeout: 300s
  build-tags:
    - tests

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cerbos/cloud-api)
      - blank
      - dot
    skip-generated: true
    custom-order: true

  gofumpt:
    extra-rules: true

  goheader:
    values:
      const:
        COMPANY: Zenauth Ltd.
    template: |-
      Copyright {{ YEAR-RANGE }} {{ COMPANY }}
      SPDX-License-Identifier: Apache-2.0

  govet:
    enable-all: true
    disable:
      - shadow

  nolintlint:
    allow-unused: false
    require-specific: true

  tagliatelle:
    case:
      rules:
        json: goCamel
        yaml: goCamel
        xml: goCamel
        bson: goCamel

  usetesting:
    os-setenv: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - goheader
    - gosec
    - govet
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - wastedassign
    - whitespace

issues:
  max-same-issues: 30

  exclude-dirs:
    - "^crypto/stream"
    - "^genpb/"
    - "^hack/"
    - "^protos/"
    - "^tools/"

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - forcetypeassert
        - goconst
        - gomnd
        - govet
        - unparam
