dir: test/mocks/{{trimPrefix "github.com/cerbos/cloud-api/" .SrcPackagePath}}
filename: "{{.InterfaceName}}.go"
pkgname: mock{{.SrcPackageName}}
structname: "{{.InterfaceName}}"
template: testify
template-data:
  boilerplate-file: hack/copyright_header.txt
packages:
  github.com/cerbos/cloud-api/genpb/cerbos/cloud/apikey/v1/apikeyv1connect:
    interfaces:
      ApiKeyServiceHandler: {}

  github.com/cerbos/cloud-api/genpb/cerbos/cloud/bundle/v1/bundlev1connect:
    interfaces:
      CerbosBundleServiceHandler: {}

  github.com/cerbos/cloud-api/genpb/cerbos/cloud/bundle/v2/bundlev2connect:
    interfaces:
      CerbosBundleServiceHandler: {}

  github.com/cerbos/cloud-api/genpb/cerbos/cloud/logs/v1/logsv1connect:
    interfaces:
      CerbosLogsServiceHandler: {}

  github.com/cerbos/cloud-api/genpb/cerbos/cloud/store/v1/storev1connect:
    interfaces:
      CerbosStoreServiceHandler: {}
