// Copyright 2021-2025 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cerbos/cloud/epdp/v2/epdp.proto

package epdpv2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	code "google.golang.org/genproto/googleapis/rpc/code"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_Schema_Enforcement int32

const (
	Config_Schema_ENFORCEMENT_UNSPECIFIED Config_Schema_Enforcement = 0
	Config_Schema_ENFORCEMENT_NONE        Config_Schema_Enforcement = 1
	Config_Schema_ENFORCEMENT_WARN        Config_Schema_Enforcement = 2
	Config_Schema_ENFORCEMENT_REJECT      Config_Schema_Enforcement = 3
)

// Enum value maps for Config_Schema_Enforcement.
var (
	Config_Schema_Enforcement_name = map[int32]string{
		0: "ENFORCEMENT_UNSPECIFIED",
		1: "ENFORCEMENT_NONE",
		2: "ENFORCEMENT_WARN",
		3: "ENFORCEMENT_REJECT",
	}
	Config_Schema_Enforcement_value = map[string]int32{
		"ENFORCEMENT_UNSPECIFIED": 0,
		"ENFORCEMENT_NONE":        1,
		"ENFORCEMENT_WARN":        2,
		"ENFORCEMENT_REJECT":      3,
	}
)

func (x Config_Schema_Enforcement) Enum() *Config_Schema_Enforcement {
	p := new(Config_Schema_Enforcement)
	*p = x
	return p
}

func (x Config_Schema_Enforcement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Schema_Enforcement) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_epdp_v2_epdp_proto_enumTypes[0].Descriptor()
}

func (Config_Schema_Enforcement) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_epdp_v2_epdp_proto_enumTypes[0]
}

func (x Config_Schema_Enforcement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Schema_Enforcement.Descriptor instead.
func (Config_Schema_Enforcement) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluator     *Config_Evaluator      `protobuf:"bytes,1,opt,name=evaluator,proto3" json:"evaluator,omitempty"`
	Schema        *Config_Schema         `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetEvaluator() *Config_Evaluator {
	if x != nil {
		return x.Evaluator
	}
	return nil
}

func (x *Config) GetSchema() *Config_Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          code.Code              `protobuf:"varint,1,opt,name=code,proto3,enum=google.rpc.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() code.Code {
	if x != nil {
		return x.Code
	}
	return code.Code(0)
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Metadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CerbosVersion    string                 `protobuf:"bytes,1,opt,name=cerbos_version,json=cerbosVersion,proto3" json:"cerbos_version,omitempty"`
	CerbosCommitHash string                 `protobuf:"bytes,2,opt,name=cerbos_commit_hash,json=cerbosCommitHash,proto3" json:"cerbos_commit_hash,omitempty"`
	WasmChecksum     string                 `protobuf:"bytes,3,opt,name=wasm_checksum,json=wasmChecksum,proto3" json:"wasm_checksum,omitempty"`
	BuiltAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetCerbosVersion() string {
	if x != nil {
		return x.CerbosVersion
	}
	return ""
}

func (x *Metadata) GetCerbosCommitHash() string {
	if x != nil {
		return x.CerbosCommitHash
	}
	return ""
}

func (x *Metadata) GetWasmChecksum() string {
	if x != nil {
		return x.WasmChecksum
	}
	return ""
}

func (x *Metadata) GetBuiltAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuiltAt
	}
	return nil
}

type Config_Evaluator struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	Globals              map[string]*structpb.Value `protobuf:"bytes,1,rep,name=globals,proto3" json:"globals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultPolicyVersion string                     `protobuf:"bytes,2,opt,name=default_policy_version,json=defaultPolicyVersion,proto3" json:"default_policy_version,omitempty"`
	LenientScopeSearch   bool                       `protobuf:"varint,3,opt,name=lenient_scope_search,json=lenientScopeSearch,proto3" json:"lenient_scope_search,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Config_Evaluator) Reset() {
	*x = Config_Evaluator{}
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Evaluator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Evaluator) ProtoMessage() {}

func (x *Config_Evaluator) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Evaluator.ProtoReflect.Descriptor instead.
func (*Config_Evaluator) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_Evaluator) GetGlobals() map[string]*structpb.Value {
	if x != nil {
		return x.Globals
	}
	return nil
}

func (x *Config_Evaluator) GetDefaultPolicyVersion() string {
	if x != nil {
		return x.DefaultPolicyVersion
	}
	return ""
}

func (x *Config_Evaluator) GetLenientScopeSearch() bool {
	if x != nil {
		return x.LenientScopeSearch
	}
	return false
}

type Config_Schema struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Enforcement   Config_Schema_Enforcement `protobuf:"varint,1,opt,name=enforcement,proto3,enum=cerbos.cloud.epdp.v2.Config_Schema_Enforcement" json:"enforcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Schema) Reset() {
	*x = Config_Schema{}
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Schema) ProtoMessage() {}

func (x *Config_Schema) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Schema.ProtoReflect.Descriptor instead.
func (*Config_Schema) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Config_Schema) GetEnforcement() Config_Schema_Enforcement {
	if x != nil {
		return x.Enforcement
	}
	return Config_Schema_ENFORCEMENT_UNSPECIFIED
}

var File_cerbos_cloud_epdp_v2_epdp_proto protoreflect.FileDescriptor

const file_cerbos_cloud_epdp_v2_epdp_proto_rawDesc = "" +
	"\n" +
	"\x1fcerbos/cloud/epdp/v2/epdp.proto\x12\x14cerbos.cloud.epdp.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15google/rpc/code.proto\"\xf2\x04\n" +
	"\x06Config\x12D\n" +
	"\tevaluator\x18\x01 \x01(\v2&.cerbos.cloud.epdp.v2.Config.EvaluatorR\tevaluator\x12;\n" +
	"\x06schema\x18\x02 \x01(\v2#.cerbos.cloud.epdp.v2.Config.SchemaR\x06schema\x1a\x96\x02\n" +
	"\tEvaluator\x12M\n" +
	"\aglobals\x18\x01 \x03(\v23.cerbos.cloud.epdp.v2.Config.Evaluator.GlobalsEntryR\aglobals\x124\n" +
	"\x16default_policy_version\x18\x02 \x01(\tR\x14defaultPolicyVersion\x120\n" +
	"\x14lenient_scope_search\x18\x03 \x01(\bR\x12lenientScopeSearch\x1aR\n" +
	"\fGlobalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1a\xcb\x01\n" +
	"\x06Schema\x12Q\n" +
	"\venforcement\x18\x01 \x01(\x0e2/.cerbos.cloud.epdp.v2.Config.Schema.EnforcementR\venforcement\"n\n" +
	"\vEnforcement\x12\x1b\n" +
	"\x17ENFORCEMENT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENFORCEMENT_NONE\x10\x01\x12\x14\n" +
	"\x10ENFORCEMENT_WARN\x10\x02\x12\x16\n" +
	"\x12ENFORCEMENT_REJECT\x10\x03\"S\n" +
	"\x05Error\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.google.rpc.CodeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe0\x01\n" +
	"\bMetadata\x12.\n" +
	"\x0ecerbos_version\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rcerbosVersion\x126\n" +
	"\x12cerbos_commit_hash\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x98\x01(R\x10cerbosCommitHash\x12-\n" +
	"\rwasm_checksum\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x98\x01@R\fwasmChecksum\x12=\n" +
	"\bbuilt_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\abuiltAtBx\n" +
	"\x1cdev.cerbos.api.cloud.v2.epdpZ=github.com/cerbos/cloud-api/genpb/cerbos/cloud/epdp/v2;epdpv2\xaa\x02\x18Cerbos.Api.Cloud.V2.Epdpb\x06proto3"

var (
	file_cerbos_cloud_epdp_v2_epdp_proto_rawDescOnce sync.Once
	file_cerbos_cloud_epdp_v2_epdp_proto_rawDescData []byte
)

func file_cerbos_cloud_epdp_v2_epdp_proto_rawDescGZIP() []byte {
	file_cerbos_cloud_epdp_v2_epdp_proto_rawDescOnce.Do(func() {
		file_cerbos_cloud_epdp_v2_epdp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbos_cloud_epdp_v2_epdp_proto_rawDesc), len(file_cerbos_cloud_epdp_v2_epdp_proto_rawDesc)))
	})
	return file_cerbos_cloud_epdp_v2_epdp_proto_rawDescData
}

var file_cerbos_cloud_epdp_v2_epdp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cerbos_cloud_epdp_v2_epdp_proto_goTypes = []any{
	(Config_Schema_Enforcement)(0), // 0: cerbos.cloud.epdp.v2.Config.Schema.Enforcement
	(*Config)(nil),                 // 1: cerbos.cloud.epdp.v2.Config
	(*Error)(nil),                  // 2: cerbos.cloud.epdp.v2.Error
	(*Metadata)(nil),               // 3: cerbos.cloud.epdp.v2.Metadata
	(*Config_Evaluator)(nil),       // 4: cerbos.cloud.epdp.v2.Config.Evaluator
	(*Config_Schema)(nil),          // 5: cerbos.cloud.epdp.v2.Config.Schema
	nil,                            // 6: cerbos.cloud.epdp.v2.Config.Evaluator.GlobalsEntry
	(code.Code)(0),                 // 7: google.rpc.Code
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*structpb.Value)(nil),         // 9: google.protobuf.Value
}
var file_cerbos_cloud_epdp_v2_epdp_proto_depIdxs = []int32{
	4, // 0: cerbos.cloud.epdp.v2.Config.evaluator:type_name -> cerbos.cloud.epdp.v2.Config.Evaluator
	5, // 1: cerbos.cloud.epdp.v2.Config.schema:type_name -> cerbos.cloud.epdp.v2.Config.Schema
	7, // 2: cerbos.cloud.epdp.v2.Error.code:type_name -> google.rpc.Code
	8, // 3: cerbos.cloud.epdp.v2.Metadata.built_at:type_name -> google.protobuf.Timestamp
	6, // 4: cerbos.cloud.epdp.v2.Config.Evaluator.globals:type_name -> cerbos.cloud.epdp.v2.Config.Evaluator.GlobalsEntry
	0, // 5: cerbos.cloud.epdp.v2.Config.Schema.enforcement:type_name -> cerbos.cloud.epdp.v2.Config.Schema.Enforcement
	9, // 6: cerbos.cloud.epdp.v2.Config.Evaluator.GlobalsEntry.value:type_name -> google.protobuf.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cerbos_cloud_epdp_v2_epdp_proto_init() }
func file_cerbos_cloud_epdp_v2_epdp_proto_init() {
	if File_cerbos_cloud_epdp_v2_epdp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbos_cloud_epdp_v2_epdp_proto_rawDesc), len(file_cerbos_cloud_epdp_v2_epdp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbos_cloud_epdp_v2_epdp_proto_goTypes,
		DependencyIndexes: file_cerbos_cloud_epdp_v2_epdp_proto_depIdxs,
		EnumInfos:         file_cerbos_cloud_epdp_v2_epdp_proto_enumTypes,
		MessageInfos:      file_cerbos_cloud_epdp_v2_epdp_proto_msgTypes,
	}.Build()
	File_cerbos_cloud_epdp_v2_epdp_proto = out.File
	file_cerbos_cloud_epdp_v2_epdp_proto_goTypes = nil
	file_cerbos_cloud_epdp_v2_epdp_proto_depIdxs = nil
}
