// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package provisionv1

import (
	protowire "google.golang.org/protobuf/encoding/protowire"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	hash "hash"
	sync "sync"
	unsafe "unsafe"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_cloud_provision_v1_CreateOrganizationRequest_hashpb_sum(m *CreateOrganizationRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateOrganizationRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_CreateOrganizationResponse_hashpb_sum(m *CreateOrganizationResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateOrganizationResponse.organization"]; !ok {
		if m.GetOrganization() != nil {
			cerbos_cloud_provision_v1_Organization_hashpb_sum(m.GetOrganization(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_CreateStoreRequest_GitHubSource_hashpb_sum(m *CreateStoreRequest_GitHubSource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.GitHubSource.repo_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetRepoId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.GitHubSource.app_installation_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetAppInstallationId())))
	}
	if m.Ref != nil {
		if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.GitHubSource.ref"]; !ok {
			switch t := m.Ref.(type) {
			case *CreateStoreRequest_GitHubSource_Branch:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.Branch))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.Branch), len(t.Branch)))
			case *CreateStoreRequest_GitHubSource_Tag:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.Tag))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.Tag), len(t.Tag)))
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.GitHubSource.subdirectory"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetSubdirectory()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetSubdirectory()), len(m.GetSubdirectory())))
	}
}

func cerbos_cloud_provision_v1_CreateStoreRequest_StoreSource_hashpb_sum(m *CreateStoreRequest_StoreSource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.StoreSource.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.StoreSource.version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetVersion())))
	}
}

func cerbos_cloud_provision_v1_CreateStoreRequest_hashpb_sum(m *CreateStoreRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.workspace"]; !ok {
		if m.GetWorkspace() != nil {
			cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m.GetWorkspace(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if m.Source != nil {
		if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreRequest.source"]; !ok {
			switch t := m.Source.(type) {
			case *CreateStoreRequest_Empty:
				if t.Empty != nil {
					google_protobuf_Empty_hashpb_sum(t.Empty, hasher, ignore, b)
				}
			case *CreateStoreRequest_Store:
				if t.Store != nil {
					cerbos_cloud_provision_v1_CreateStoreRequest_StoreSource_hashpb_sum(t.Store, hasher, ignore, b)
				}
			case *CreateStoreRequest_Github:
				if t.Github != nil {
					cerbos_cloud_provision_v1_CreateStoreRequest_GitHubSource_hashpb_sum(t.Github, hasher, ignore, b)
				}
			}
		}
	}
}

func cerbos_cloud_provision_v1_CreateStoreResponse_hashpb_sum(m *CreateStoreResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateStoreResponse.store"]; !ok {
		if m.GetStore() != nil {
			cerbos_cloud_provision_v1_Store_hashpb_sum(m.GetStore(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_CreateWorkspaceRequest_hashpb_sum(m *CreateWorkspaceRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateWorkspaceRequest.organization"]; !ok {
		if m.GetOrganization() != nil {
			cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m.GetOrganization(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateWorkspaceRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_CreateWorkspaceResponse_hashpb_sum(m *CreateWorkspaceResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.CreateWorkspaceResponse.workspace"]; !ok {
		if m.GetWorkspace() != nil {
			cerbos_cloud_provision_v1_Workspace_hashpb_sum(m.GetWorkspace(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_DeleteOrganizationRequest_hashpb_sum(m *DeleteOrganizationRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.DeleteOrganizationRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_DeleteOrganizationResponse_hashpb_sum(m *DeleteOrganizationResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
}

func cerbos_cloud_provision_v1_DeleteStoreRequest_hashpb_sum(m *DeleteStoreRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.DeleteStoreRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_DeleteStoreResponse_hashpb_sum(m *DeleteStoreResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
}

func cerbos_cloud_provision_v1_DeleteWorkspaceRequest_hashpb_sum(m *DeleteWorkspaceRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.DeleteWorkspaceRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_DeleteWorkspaceResponse_hashpb_sum(m *DeleteWorkspaceResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
}

func cerbos_cloud_provision_v1_Organization_hashpb_sum(m *Organization, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Organization.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Organization.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_ReadOrganizationRequest_hashpb_sum(m *ReadOrganizationRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadOrganizationRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_ReadOrganizationResponse_hashpb_sum(m *ReadOrganizationResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadOrganizationResponse.organization"]; !ok {
		if m.GetOrganization() != nil {
			cerbos_cloud_provision_v1_Organization_hashpb_sum(m.GetOrganization(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_ReadStoreRequest_hashpb_sum(m *ReadStoreRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadStoreRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_ReadStoreResponse_hashpb_sum(m *ReadStoreResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadStoreResponse.store"]; !ok {
		if m.GetStore() != nil {
			cerbos_cloud_provision_v1_Store_hashpb_sum(m.GetStore(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_ReadWorkspaceRequest_hashpb_sum(m *ReadWorkspaceRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadWorkspaceRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_ReadWorkspaceResponse_hashpb_sum(m *ReadWorkspaceResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.ReadWorkspaceResponse.workspace"]; !ok {
		if m.GetWorkspace() != nil {
			cerbos_cloud_provision_v1_Workspace_hashpb_sum(m.GetWorkspace(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_Resource_Deployment_hashpb_sum(m *Resource_Deployment, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Deployment.organization_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetOrganizationId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetOrganizationId()), len(m.GetOrganizationId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Deployment.workspace_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetWorkspaceId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetWorkspaceId()), len(m.GetWorkspaceId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Deployment.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
}

func cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m *Resource_Organization, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Organization.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
}

func cerbos_cloud_provision_v1_Resource_Playground_hashpb_sum(m *Resource_Playground, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Playground.organization_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetOrganizationId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetOrganizationId()), len(m.GetOrganizationId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Playground.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
}

func cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(m *Resource_Store, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Store.organization_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetOrganizationId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetOrganizationId()), len(m.GetOrganizationId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Store.workspace_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetWorkspaceId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetWorkspaceId()), len(m.GetWorkspaceId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Store.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
}

func cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m *Resource_Workspace, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Workspace.organization_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetOrganizationId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetOrganizationId()), len(m.GetOrganizationId())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Resource.Workspace.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
}

func cerbos_cloud_provision_v1_Resource_hashpb_sum(m *Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if m.Kind != nil {
		if _, ok := ignore["cerbos.cloud.provision.v1.Resource.kind"]; !ok {
			switch t := m.Kind.(type) {
			case *Resource_Organization_:
				if t.Organization != nil {
					cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(t.Organization, hasher, ignore, b)
				}
			case *Resource_Workspace_:
				if t.Workspace != nil {
					cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(t.Workspace, hasher, ignore, b)
				}
			case *Resource_Playground_:
				if t.Playground != nil {
					cerbos_cloud_provision_v1_Resource_Playground_hashpb_sum(t.Playground, hasher, ignore, b)
				}
			case *Resource_Store_:
				if t.Store != nil {
					cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(t.Store, hasher, ignore, b)
				}
			case *Resource_Deployment_:
				if t.Deployment != nil {
					cerbos_cloud_provision_v1_Resource_Deployment_hashpb_sum(t.Deployment, hasher, ignore, b)
				}
			}
		}
	}
}

func cerbos_cloud_provision_v1_Store_hashpb_sum(m *Store, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Store.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Store.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Store.version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetVersion())))
	}
}

func cerbos_cloud_provision_v1_UpdateOrganizationRequest_hashpb_sum(m *UpdateOrganizationRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateOrganizationRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Organization_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateOrganizationRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_UpdateOrganizationResponse_hashpb_sum(m *UpdateOrganizationResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateOrganizationResponse.organization"]; !ok {
		if m.GetOrganization() != nil {
			cerbos_cloud_provision_v1_Organization_hashpb_sum(m.GetOrganization(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_UpdateStoreRequest_hashpb_sum(m *UpdateStoreRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateStoreRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Store_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateStoreRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_UpdateStoreResponse_hashpb_sum(m *UpdateStoreResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateStoreResponse.store"]; !ok {
		if m.GetStore() != nil {
			cerbos_cloud_provision_v1_Store_hashpb_sum(m.GetStore(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_UpdateWorkspaceRequest_hashpb_sum(m *UpdateWorkspaceRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateWorkspaceRequest.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateWorkspaceRequest.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func cerbos_cloud_provision_v1_UpdateWorkspaceResponse_hashpb_sum(m *UpdateWorkspaceResponse, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.UpdateWorkspaceResponse.workspace"]; !ok {
		if m.GetWorkspace() != nil {
			cerbos_cloud_provision_v1_Workspace_hashpb_sum(m.GetWorkspace(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_provision_v1_Workspace_hashpb_sum(m *Workspace, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.provision.v1.Workspace.resource_id"]; !ok {
		if m.GetResourceId() != nil {
			cerbos_cloud_provision_v1_Resource_Workspace_hashpb_sum(m.GetResourceId(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.provision.v1.Workspace.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
}

func google_protobuf_Empty_hashpb_sum(m *emptypb.Empty, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
}
