// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cerbos/cloud/provision/v1/provision.proto

package provisionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cerbos/cloud-api/genpb/cerbos/cloud/provision/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CerbosHubProvisioningServiceName is the fully-qualified name of the CerbosHubProvisioningService
	// service.
	CerbosHubProvisioningServiceName = "cerbos.cloud.provision.v1.CerbosHubProvisioningService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CerbosHubProvisioningServiceCreateOrganizationProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's CreateOrganization RPC.
	CerbosHubProvisioningServiceCreateOrganizationProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/CreateOrganization"
	// CerbosHubProvisioningServiceReadOrganizationProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's ReadOrganization RPC.
	CerbosHubProvisioningServiceReadOrganizationProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/ReadOrganization"
	// CerbosHubProvisioningServiceUpdateOrganizationProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's UpdateOrganization RPC.
	CerbosHubProvisioningServiceUpdateOrganizationProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/UpdateOrganization"
	// CerbosHubProvisioningServiceDeleteOrganizationProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's DeleteOrganization RPC.
	CerbosHubProvisioningServiceDeleteOrganizationProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/DeleteOrganization"
	// CerbosHubProvisioningServiceCreateWorkspaceProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's CreateWorkspace RPC.
	CerbosHubProvisioningServiceCreateWorkspaceProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/CreateWorkspace"
	// CerbosHubProvisioningServiceReadWorkspaceProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's ReadWorkspace RPC.
	CerbosHubProvisioningServiceReadWorkspaceProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/ReadWorkspace"
	// CerbosHubProvisioningServiceUpdateWorkspaceProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's UpdateWorkspace RPC.
	CerbosHubProvisioningServiceUpdateWorkspaceProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/UpdateWorkspace"
	// CerbosHubProvisioningServiceDeleteWorkspaceProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's DeleteWorkspace RPC.
	CerbosHubProvisioningServiceDeleteWorkspaceProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/DeleteWorkspace"
	// CerbosHubProvisioningServiceCreateStoreProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's CreateStore RPC.
	CerbosHubProvisioningServiceCreateStoreProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/CreateStore"
	// CerbosHubProvisioningServiceReadStoreProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's ReadStore RPC.
	CerbosHubProvisioningServiceReadStoreProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/ReadStore"
	// CerbosHubProvisioningServiceUpdateStoreProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's UpdateStore RPC.
	CerbosHubProvisioningServiceUpdateStoreProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/UpdateStore"
	// CerbosHubProvisioningServiceDeleteStoreProcedure is the fully-qualified name of the
	// CerbosHubProvisioningService's DeleteStore RPC.
	CerbosHubProvisioningServiceDeleteStoreProcedure = "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/DeleteStore"
)

// CerbosHubProvisioningServiceClient is a client for the
// cerbos.cloud.provision.v1.CerbosHubProvisioningService service.
type CerbosHubProvisioningServiceClient interface {
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	ReadOrganization(context.Context, *connect.Request[v1.ReadOrganizationRequest]) (*connect.Response[v1.ReadOrganizationResponse], error)
	UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error)
	DeleteOrganization(context.Context, *connect.Request[v1.DeleteOrganizationRequest]) (*connect.Response[v1.DeleteOrganizationResponse], error)
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	ReadWorkspace(context.Context, *connect.Request[v1.ReadWorkspaceRequest]) (*connect.Response[v1.ReadWorkspaceResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	CreateStore(context.Context, *connect.Request[v1.CreateStoreRequest]) (*connect.Response[v1.CreateStoreResponse], error)
	ReadStore(context.Context, *connect.Request[v1.ReadStoreRequest]) (*connect.Response[v1.ReadStoreResponse], error)
	UpdateStore(context.Context, *connect.Request[v1.UpdateStoreRequest]) (*connect.Response[v1.UpdateStoreResponse], error)
	DeleteStore(context.Context, *connect.Request[v1.DeleteStoreRequest]) (*connect.Response[v1.DeleteStoreResponse], error)
}

// NewCerbosHubProvisioningServiceClient constructs a client for the
// cerbos.cloud.provision.v1.CerbosHubProvisioningService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCerbosHubProvisioningServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CerbosHubProvisioningServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cerbosHubProvisioningServiceMethods := v1.File_cerbos_cloud_provision_v1_provision_proto.Services().ByName("CerbosHubProvisioningService").Methods()
	return &cerbosHubProvisioningServiceClient{
		createOrganization: connect.NewClient[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceCreateOrganizationProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		readOrganization: connect.NewClient[v1.ReadOrganizationRequest, v1.ReadOrganizationResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceReadOrganizationProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadOrganization")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateOrganization: connect.NewClient[v1.UpdateOrganizationRequest, v1.UpdateOrganizationResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceUpdateOrganizationProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateOrganization")),
			connect.WithClientOptions(opts...),
		),
		deleteOrganization: connect.NewClient[v1.DeleteOrganizationRequest, v1.DeleteOrganizationResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceDeleteOrganizationProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteOrganization")),
			connect.WithClientOptions(opts...),
		),
		createWorkspace: connect.NewClient[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceCreateWorkspaceProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		readWorkspace: connect.NewClient[v1.ReadWorkspaceRequest, v1.ReadWorkspaceResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceReadWorkspaceProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadWorkspace")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateWorkspace: connect.NewClient[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceUpdateWorkspaceProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		deleteWorkspace: connect.NewClient[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceDeleteWorkspaceProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteWorkspace")),
			connect.WithClientOptions(opts...),
		),
		createStore: connect.NewClient[v1.CreateStoreRequest, v1.CreateStoreResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceCreateStoreProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateStore")),
			connect.WithClientOptions(opts...),
		),
		readStore: connect.NewClient[v1.ReadStoreRequest, v1.ReadStoreResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceReadStoreProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadStore")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateStore: connect.NewClient[v1.UpdateStoreRequest, v1.UpdateStoreResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceUpdateStoreProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateStore")),
			connect.WithClientOptions(opts...),
		),
		deleteStore: connect.NewClient[v1.DeleteStoreRequest, v1.DeleteStoreResponse](
			httpClient,
			baseURL+CerbosHubProvisioningServiceDeleteStoreProcedure,
			connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteStore")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cerbosHubProvisioningServiceClient implements CerbosHubProvisioningServiceClient.
type cerbosHubProvisioningServiceClient struct {
	createOrganization *connect.Client[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse]
	readOrganization   *connect.Client[v1.ReadOrganizationRequest, v1.ReadOrganizationResponse]
	updateOrganization *connect.Client[v1.UpdateOrganizationRequest, v1.UpdateOrganizationResponse]
	deleteOrganization *connect.Client[v1.DeleteOrganizationRequest, v1.DeleteOrganizationResponse]
	createWorkspace    *connect.Client[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse]
	readWorkspace      *connect.Client[v1.ReadWorkspaceRequest, v1.ReadWorkspaceResponse]
	updateWorkspace    *connect.Client[v1.UpdateWorkspaceRequest, v1.UpdateWorkspaceResponse]
	deleteWorkspace    *connect.Client[v1.DeleteWorkspaceRequest, v1.DeleteWorkspaceResponse]
	createStore        *connect.Client[v1.CreateStoreRequest, v1.CreateStoreResponse]
	readStore          *connect.Client[v1.ReadStoreRequest, v1.ReadStoreResponse]
	updateStore        *connect.Client[v1.UpdateStoreRequest, v1.UpdateStoreResponse]
	deleteStore        *connect.Client[v1.DeleteStoreRequest, v1.DeleteStoreResponse]
}

// CreateOrganization calls
// cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateOrganization.
func (c *cerbosHubProvisioningServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// ReadOrganization calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadOrganization.
func (c *cerbosHubProvisioningServiceClient) ReadOrganization(ctx context.Context, req *connect.Request[v1.ReadOrganizationRequest]) (*connect.Response[v1.ReadOrganizationResponse], error) {
	return c.readOrganization.CallUnary(ctx, req)
}

// UpdateOrganization calls
// cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateOrganization.
func (c *cerbosHubProvisioningServiceClient) UpdateOrganization(ctx context.Context, req *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error) {
	return c.updateOrganization.CallUnary(ctx, req)
}

// DeleteOrganization calls
// cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteOrganization.
func (c *cerbosHubProvisioningServiceClient) DeleteOrganization(ctx context.Context, req *connect.Request[v1.DeleteOrganizationRequest]) (*connect.Response[v1.DeleteOrganizationResponse], error) {
	return c.deleteOrganization.CallUnary(ctx, req)
}

// CreateWorkspace calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateWorkspace.
func (c *cerbosHubProvisioningServiceClient) CreateWorkspace(ctx context.Context, req *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return c.createWorkspace.CallUnary(ctx, req)
}

// ReadWorkspace calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadWorkspace.
func (c *cerbosHubProvisioningServiceClient) ReadWorkspace(ctx context.Context, req *connect.Request[v1.ReadWorkspaceRequest]) (*connect.Response[v1.ReadWorkspaceResponse], error) {
	return c.readWorkspace.CallUnary(ctx, req)
}

// UpdateWorkspace calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateWorkspace.
func (c *cerbosHubProvisioningServiceClient) UpdateWorkspace(ctx context.Context, req *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return c.updateWorkspace.CallUnary(ctx, req)
}

// DeleteWorkspace calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteWorkspace.
func (c *cerbosHubProvisioningServiceClient) DeleteWorkspace(ctx context.Context, req *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return c.deleteWorkspace.CallUnary(ctx, req)
}

// CreateStore calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateStore.
func (c *cerbosHubProvisioningServiceClient) CreateStore(ctx context.Context, req *connect.Request[v1.CreateStoreRequest]) (*connect.Response[v1.CreateStoreResponse], error) {
	return c.createStore.CallUnary(ctx, req)
}

// ReadStore calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadStore.
func (c *cerbosHubProvisioningServiceClient) ReadStore(ctx context.Context, req *connect.Request[v1.ReadStoreRequest]) (*connect.Response[v1.ReadStoreResponse], error) {
	return c.readStore.CallUnary(ctx, req)
}

// UpdateStore calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateStore.
func (c *cerbosHubProvisioningServiceClient) UpdateStore(ctx context.Context, req *connect.Request[v1.UpdateStoreRequest]) (*connect.Response[v1.UpdateStoreResponse], error) {
	return c.updateStore.CallUnary(ctx, req)
}

// DeleteStore calls cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteStore.
func (c *cerbosHubProvisioningServiceClient) DeleteStore(ctx context.Context, req *connect.Request[v1.DeleteStoreRequest]) (*connect.Response[v1.DeleteStoreResponse], error) {
	return c.deleteStore.CallUnary(ctx, req)
}

// CerbosHubProvisioningServiceHandler is an implementation of the
// cerbos.cloud.provision.v1.CerbosHubProvisioningService service.
type CerbosHubProvisioningServiceHandler interface {
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	ReadOrganization(context.Context, *connect.Request[v1.ReadOrganizationRequest]) (*connect.Response[v1.ReadOrganizationResponse], error)
	UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error)
	DeleteOrganization(context.Context, *connect.Request[v1.DeleteOrganizationRequest]) (*connect.Response[v1.DeleteOrganizationResponse], error)
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	ReadWorkspace(context.Context, *connect.Request[v1.ReadWorkspaceRequest]) (*connect.Response[v1.ReadWorkspaceResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error)
	DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error)
	CreateStore(context.Context, *connect.Request[v1.CreateStoreRequest]) (*connect.Response[v1.CreateStoreResponse], error)
	ReadStore(context.Context, *connect.Request[v1.ReadStoreRequest]) (*connect.Response[v1.ReadStoreResponse], error)
	UpdateStore(context.Context, *connect.Request[v1.UpdateStoreRequest]) (*connect.Response[v1.UpdateStoreResponse], error)
	DeleteStore(context.Context, *connect.Request[v1.DeleteStoreRequest]) (*connect.Response[v1.DeleteStoreResponse], error)
}

// NewCerbosHubProvisioningServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCerbosHubProvisioningServiceHandler(svc CerbosHubProvisioningServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cerbosHubProvisioningServiceMethods := v1.File_cerbos_cloud_provision_v1_provision_proto.Services().ByName("CerbosHubProvisioningService").Methods()
	cerbosHubProvisioningServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceReadOrganizationHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceReadOrganizationProcedure,
		svc.ReadOrganization,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadOrganization")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceUpdateOrganizationHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceUpdateOrganizationProcedure,
		svc.UpdateOrganization,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceDeleteOrganizationHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceDeleteOrganizationProcedure,
		svc.DeleteOrganization,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceCreateWorkspaceHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceCreateWorkspaceProcedure,
		svc.CreateWorkspace,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceReadWorkspaceHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceReadWorkspaceProcedure,
		svc.ReadWorkspace,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadWorkspace")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceUpdateWorkspaceHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceUpdateWorkspaceProcedure,
		svc.UpdateWorkspace,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceDeleteWorkspaceHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceDeleteWorkspaceProcedure,
		svc.DeleteWorkspace,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceCreateStoreHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceCreateStoreProcedure,
		svc.CreateStore,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("CreateStore")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceReadStoreHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceReadStoreProcedure,
		svc.ReadStore,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("ReadStore")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceUpdateStoreHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceUpdateStoreProcedure,
		svc.UpdateStore,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("UpdateStore")),
		connect.WithHandlerOptions(opts...),
	)
	cerbosHubProvisioningServiceDeleteStoreHandler := connect.NewUnaryHandler(
		CerbosHubProvisioningServiceDeleteStoreProcedure,
		svc.DeleteStore,
		connect.WithSchema(cerbosHubProvisioningServiceMethods.ByName("DeleteStore")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cerbos.cloud.provision.v1.CerbosHubProvisioningService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CerbosHubProvisioningServiceCreateOrganizationProcedure:
			cerbosHubProvisioningServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceReadOrganizationProcedure:
			cerbosHubProvisioningServiceReadOrganizationHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceUpdateOrganizationProcedure:
			cerbosHubProvisioningServiceUpdateOrganizationHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceDeleteOrganizationProcedure:
			cerbosHubProvisioningServiceDeleteOrganizationHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceCreateWorkspaceProcedure:
			cerbosHubProvisioningServiceCreateWorkspaceHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceReadWorkspaceProcedure:
			cerbosHubProvisioningServiceReadWorkspaceHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceUpdateWorkspaceProcedure:
			cerbosHubProvisioningServiceUpdateWorkspaceHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceDeleteWorkspaceProcedure:
			cerbosHubProvisioningServiceDeleteWorkspaceHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceCreateStoreProcedure:
			cerbosHubProvisioningServiceCreateStoreHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceReadStoreProcedure:
			cerbosHubProvisioningServiceReadStoreHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceUpdateStoreProcedure:
			cerbosHubProvisioningServiceUpdateStoreHandler.ServeHTTP(w, r)
		case CerbosHubProvisioningServiceDeleteStoreProcedure:
			cerbosHubProvisioningServiceDeleteStoreHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCerbosHubProvisioningServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCerbosHubProvisioningServiceHandler struct{}

func (UnimplementedCerbosHubProvisioningServiceHandler) CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateOrganization is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) ReadOrganization(context.Context, *connect.Request[v1.ReadOrganizationRequest]) (*connect.Response[v1.ReadOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadOrganization is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) UpdateOrganization(context.Context, *connect.Request[v1.UpdateOrganizationRequest]) (*connect.Response[v1.UpdateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateOrganization is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) DeleteOrganization(context.Context, *connect.Request[v1.DeleteOrganizationRequest]) (*connect.Response[v1.DeleteOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteOrganization is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateWorkspace is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) ReadWorkspace(context.Context, *connect.Request[v1.ReadWorkspaceRequest]) (*connect.Response[v1.ReadWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadWorkspace is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) UpdateWorkspace(context.Context, *connect.Request[v1.UpdateWorkspaceRequest]) (*connect.Response[v1.UpdateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateWorkspace is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) DeleteWorkspace(context.Context, *connect.Request[v1.DeleteWorkspaceRequest]) (*connect.Response[v1.DeleteWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteWorkspace is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) CreateStore(context.Context, *connect.Request[v1.CreateStoreRequest]) (*connect.Response[v1.CreateStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.CreateStore is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) ReadStore(context.Context, *connect.Request[v1.ReadStoreRequest]) (*connect.Response[v1.ReadStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.ReadStore is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) UpdateStore(context.Context, *connect.Request[v1.UpdateStoreRequest]) (*connect.Response[v1.UpdateStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.UpdateStore is not implemented"))
}

func (UnimplementedCerbosHubProvisioningServiceHandler) DeleteStore(context.Context, *connect.Request[v1.DeleteStoreRequest]) (*connect.Response[v1.DeleteStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.provision.v1.CerbosHubProvisioningService.DeleteStore is not implemented"))
}
