// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package bootstrapv1

import (
	v1 "github.com/cerbos/cloud-api/genpb/cerbos/cloud/bundle/v1"
	protowire "google.golang.org/protobuf/encoding/protowire"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	hash "hash"
	sync "sync"
	unsafe "unsafe"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_cloud_bootstrap_v1_PDPConfig_Meta_hashpb_sum(m *PDPConfig_Meta, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.bootstrap.v1.PDPConfig.Meta.created_at"]; !ok {
		if m.GetCreatedAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetCreatedAt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.bootstrap.v1.PDPConfig.Meta.commit_hash"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetCommitHash()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetCommitHash()), len(m.GetCommitHash())))
	}
}

func cerbos_cloud_bootstrap_v1_PDPConfig_hashpb_sum(m *PDPConfig, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.bootstrap.v1.PDPConfig.meta"]; !ok {
		if m.GetMeta() != nil {
			cerbos_cloud_bootstrap_v1_PDPConfig_Meta_hashpb_sum(m.GetMeta(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.bootstrap.v1.PDPConfig.bundle_info"]; !ok {
		if m.GetBundleInfo() != nil {
			cerbos_cloud_bundle_v1_BundleInfo_hashpb_sum(m.GetBundleInfo(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_bundle_v1_BundleInfo_Segment_hashpb_sum(m *v1.BundleInfo_Segment, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.Segment.segment_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSegmentId())))
	}
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.Segment.checksum"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetChecksum()))))
		_, _ = hasher.Write(m.GetChecksum())
	}
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.Segment.download_urls"]; !ok {
		if len(m.DownloadUrls) > 0 {
			for _, v := range m.DownloadUrls {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
}

func cerbos_cloud_bundle_v1_BundleInfo_hashpb_sum(m *v1.BundleInfo, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.label"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetLabel()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetLabel()), len(m.GetLabel())))
	}
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.bundle_hash"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetBundleHash()))))
		_, _ = hasher.Write(m.GetBundleHash())
	}
	if _, ok := ignore["cerbos.cloud.bundle.v1.BundleInfo.segments"]; !ok {
		if len(m.Segments) > 0 {
			for _, v := range m.Segments {
				if v != nil {
					cerbos_cloud_bundle_v1_BundleInfo_Segment_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Timestamp.seconds"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeconds())))
	}
	if _, ok := ignore["google.protobuf.Timestamp.nanos"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetNanos())))
	}
}
