// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/cloud/auth/v1/auth.proto

package authv1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ClientCredentials) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_auth_v1_ClientCredentials_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeviceToken) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_auth_v1_DeviceToken_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SavedCredentials) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_auth_v1_SavedCredentials_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}
