// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.4.2

package pdpv1

import (
	protowire "google.golang.org/protobuf/encoding/protowire"
	hash "hash"
	unsafe "unsafe"
)

func cerbos_cloud_pdp_v1_Identifier_hashpb_sum(m *Identifier, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["cerbos.cloud.pdp.v1.Identifier.instance"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetInstance()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetInstance()), len(m.GetInstance())))
	}
	if _, ok := ignore["cerbos.cloud.pdp.v1.Identifier.version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetVersion()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetVersion()), len(m.GetVersion())))
	}
}
