---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "v*"
defaults:
  run:
    shell: bash
permissions: {}
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    name: Test on Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go }}
          cache: false
          check-latest: true

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up just
        uses: cerbos/actions/install-tools@120749e918c919283f71ea19b06a2f0637132e06 # main
        with:
          tools: just

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/cerbos-cloud-api/bin
          key: generate-${{ runner.os }}-go-${{matrix.go}}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            generate-${{ runner.os }}-go-${{matrix.go}}-

      - name: Test
        run: just test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Set up just
        uses: cerbos/actions/install-tools@120749e918c919283f71ea19b06a2f0637132e06 # main
        with:
          tools: just

      - name: modernize
        run: just lint-modernize

      - name: golangci-lint
        uses: cerbos/actions/golangci-lint@120749e918c919283f71ea19b06a2f0637132e06 # main

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@120749e918c919283f71ea19b06a2f0637132e06 # main

  buf:
    name: Proto check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint protos
        uses: cerbos/actions/buf@120749e918c919283f71ea19b06a2f0637132e06 # main
