---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "v*"
defaults:
  run:
    shell: bash
permissions: {}
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    name: Test on Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}
          cache: false
          check-latest: true

      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Set up just
        uses: cerbos/actions/install-tools@7df6503218a73e5022cc801e99574380474c97dd # main
        with:
          tools: just

      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/cerbos-cloud-api/bin
          key: generate-${{ runner.os }}-go-${{matrix.go}}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            generate-${{ runner.os }}-go-${{matrix.go}}-

      - name: Test
        run: just test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Set up just
        uses: cerbos/actions/install-tools@7df6503218a73e5022cc801e99574380474c97dd # main
        with:
          tools: just

      - name: modernize
        run: just lint-modernize

      - name: golangci-lint
        uses: cerbos/actions/golangci-lint@7df6503218a73e5022cc801e99574380474c97dd # main

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@7df6503218a73e5022cc801e99574380474c97dd # main

  buf:
    name: Proto check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Lint protos
        uses: cerbos/actions/buf@7df6503218a73e5022cc801e99574380474c97dd # main
