---
name: Publish
on:
  push:
    branches:
      - main
    tags:
      - v*
defaults:
  run:
    shell: bash
permissions: {}
jobs:
  publishProtos:
    name: Publish Protobufs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Push to BSR
        uses: cerbos/actions/buf@6e173289a5f7dbcc0a62e6cb761e18f22f0b2070 # main
        with:
          token: ${{ secrets.BUF_TOKEN }}
