---
name: Publish
on:
  push:
    branches:
      - main
    tags:
      - v*
defaults:
  run:
    shell: bash
permissions: {}
jobs:
  publishProtos:
    name: Publish Protobufs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Push to BSR
        uses: cerbos/actions/buf@d2c46d81505b3c938d9eaa51af6d5ef4020cd4bf # main
        with:
          token: ${{ secrets.BUF_TOKEN }}
